{{- range .Values.mongodbs }}
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .name }}-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.8"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: user
      db: {{ .name }}
      passwordSecretRef:
        name: {{ .name }}-mongodb-initial-password
      roles:
        - name: dbOwner
          db: {{ .name }}
      scramCredentialsSecretName: {{ .name }}-mongodb-scram
      connectionStringSecretName: {{ .name }}-mongodb-connection-string
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    systemLog.quiet: false
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "1"
                  memory: 1Gi
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
---
{{- $password := randAlphaNum 24 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-mongodb-initial-password
type: Opaque
stringData:
  password: {{ $password }}
{{- end -}}
