{{- range .Values.mongodbs }}
{{ $mongodb := .}}
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .name }}-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.8"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    {{- range .users }}
    - name: {{ .name  }}
      db: {{ .db }}
      passwordSecretRef:
        name: {{ $mongodb.name }}-{{ .name }}-mongodb-initial-password
      roles:
        - name: dbOwner
          db: {{ .db }}
      scramCredentialsSecretName: {{ $mongodb.name }}-{{ .name }}-mongodb-scram
      connectionStringSecretName: {{ $mongodb.name }}-{{ .name }}-mongodb-connection-string
    {{- end}}
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    systemLog.quiet: false
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            resources:
              requests:
                storage: 1Gi
        - metadata:
            name: logs-volume
          spec:
            resources:
              requests:
                storage: 1Gi
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "0.9"
                  memory: 800Mi
                requests:
                  cpu: "0.25"
                  memory: 500Mi
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.1"
                  memory: 200M
                requests:
                  cpu: "0.1"
                  memory: 200M
{{- end -}}
