addr: ""
password: ""

sts:
  image:
    name: "simplexchat/smp-server"
    tag: "latest"
#   pullPolicy: "Always"
 resources:
   requests:
     cpu: "100m"
     memory: "100Mi"
   limits:
     cpu: "1"
     memory: "1Gi"
# replicas: 1
# env: []
# targetPort: 5223
# imagePullSecrets: "regcred"

pvc:
  config:
    size: 3Gi
  logs:
    size: 3Gi

svc:
  type: "ClusterIP"

