apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --insecure-oidc-allow-unverified-email
        - --cookie-domain={{ .Values.host }}
        - --whitelist-domain={{ .Values.host }}
        - --upstream=http://any/
        - --http-address=0.0.0.0:4180
        - --provider-ca-file=/etc/ssl/self-signed.pem
        - --session-store-type=redis
        - --redis-connection-url=redis://localhost:6379
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: cookie-secret
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://{{ .Values.host }}/oauth2/callback"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: {{ .Values.issuer_url | quote  }}
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/ssl/self-signed.pem
          name: self-signed-cert
          subPath: self-signed.pem
      - image: redis:6.2.6-alpine
        name: redis
      volumes:
      - name: self-signed-cert
        configMap:
          name: self-signed-cert
          items:
          - key: self-signed.pem
            path: self-signed.pem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: self-signed-cert
data:
  self-signed.pem: |
    -----BEGIN CERTIFICATE-----
    MIIBnDCCAUKgAwIBAgIRAIWibNCjOegYY5QgAGA6n9YwCgYIKoZIzj0EAwIwLDEQ
    MA4GA1UEChMHQ3JvbkxpYjEYMBYGA1UEAxMPQ3JvbkxpYiBSb290IENBMB4XDTI0
    MDIwOTAyMDAyOFoXDTM0MDIwNjAyMDAyOFowLDEQMA4GA1UEChMHQ3JvbkxpYjEY
    MBYGA1UEAxMPQ3JvbkxpYiBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
    QgAExnEIl2pOoq6tzIWE8xzRR5gd4x989h8NO2yGa4fDMRFhMi8X6JNQ2WhF2hxq
    p3BwSxB/dV3V3DWj+Wn/qs81MaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
    /wQIMAYBAf8CAQEwHQYDVR0OBBYEFLCURr5kPvLini/6I9o9OYXXjiKIMAoGCCqG
    SM49BAMCA0gAMEUCID23h3Qv69kYVPghMtldlAg1ERUWN8bM3ukDVKCjZhe+AiEA
    o+qg435+LN73lY70pmjVu8akDzz4DJDBiDJjeuRdiJw=
    -----END CERTIFICATE-----
