{{ $values := .Values }}
{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .name }}-sts"
spec:
  replicas: {{ .replicas | default 1 }}
  serviceName: {{ .name | quote }}
  selector:
    matchLabels:
      app: {{ .name | quote }}
  template:
    metadata:
      labels:
        app: {{ .name | quote }}
    spec:
      containers:
        - name: container
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
          volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
            readOnly: true
          resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .service }}
          {{- if .enabled }}
          ports:
          - containerPort: {{ .targetPort | default 8080 }}
          {{- end }}
          {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: "{{ .name }}-cm"
      imagePullSecrets:
      - name: regcred
{{- end -}}
