apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refmd.fullname" . }}
  labels:
    {{- include "refmd.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.refmd.api.jwtSecret | b64enc | quote }}
  {{- $databaseUrl := include "refmd.databaseUrl" . }}
  {{- if $databaseUrl }}
  DATABASE_URL: {{ $databaseUrl | b64enc | quote }}
  {{- end }}