apiVersion: v1
kind: Service
metadata:
  name: {{ include "refmd.fullname" . }}-api
  labels:
    {{- include "refmd.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "refmd.api.selectorLabels" . | nindent 4 }}