apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-js
data:
  mongo-init.js: |-
    print("Started Adding the Users.");
    db = db.getSiblingDB("admin");
    {{- range .Values.users }}
    if (!db.getUser("{{ .name }}")) {
      db.createUser({
        user: "{{ .name }}",
        pwd: "{{ .pass }}",
        roles: [{ role: "dbOwner", db: "{{ .db }}" }],
      });
    }
    {{- end }}
    print("End Adding the User Roles.");
