{{ $values := .Values }}
{{- with .Values.sts.smp }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "smp-server"
spec:
  replicas: {{ .replicas | default 1 }}
  serviceName: "simplex"
  selector:
    matchLabels:
      app: "simplex"
  template:
    metadata:
      labels:
        app: "simplex"
    spec:
      containers:
        - name: container
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
          volumeMounts:
            - mountPath: /etc/opt/simplex
              name: "config-volume"
            - mountPath: /var/opt/simplex
              name: "logs-volume"
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
          env:
            - name: "ADDR"
              value: {{ $values.addr }}
            - name: "PASS"
              value: {{ $values.password }}
          {{- with .env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: {{ .targetPort | default 5223 }}
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: "smp-config-pvc"
      - name: logs-volume
        persistentVolumeClaim:
          claimName: "smp-logs-pvc"
      {{- with .imagePullSecrets }}
      imagePullSecrets:
      - name: {{ . | quote  }}
      {{- end }}
{{- end }}
