{{- with .Values.svc }}
apiVersion: v1
kind: Service
metadata:
  name: simplex-svc
  labels:
    app: simplex
spec:
  ports:
    - name: smp
      port: 5223
      targetPort: 5223
    - name: xftp
      port: 443
      targetPort: 443
  type: {{ .type | quote }}
  selector:
    app: simplex
{{- end }}
