{{- with .Values.pvc.xftp}}
{{- with .config }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xftp-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size  }}
{{- end }}
{{- with .logs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xftp-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size}}
{{- end }}
{{- with .files }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xftp-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size}}
{{- end }}

{{- end }}
